### ISSUE TITLE
Tips to Make install easier

### ISSUE THREAD

**Issue by go9girl** [unarmedtuna/INFRA-Multiplayer-2023#1]
You can upload releases bigger than 25 mb so you can make install easier by putting everything that needs to go in the infra folder into a zip file, so someone can just dump the contents into the common/infra folder

**Comment by go9girl** [comment]
can you also upload your new code?

**Comment by unarmedtuna** [comment]
check out the 2024 V0.0.1  respiratory here
<https://github.com/unarmedtuna/INFRA-Multiplayer-2024-V-0.0.1>

**Comment by go9girl** [comment]
Sry for the late response. Thank you for the great work, you should also be able to put it up as a release to save on some google drive spacr.
